### ISSUE TITLE
use reasonml / ocaml rather than js / typescript / @ts-check to capture requirements?

### ISSUE THREAD

**Issue by dckc** [rchain-community/daw205#4]
So far, this exploration is using a [@ts-check dialect of js](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html) that supports static analysis with the typescript compiler. I find it to be a pretty good compromise between a type system to support correct-by-construction and the actual runtime environments in the web.

But collaboration with @leithaus (for example, using types to capture requirements) might be smoother using [reasoml](https://reasonml.github.io/), i.e. ocaml compiled to js. During a brief time when I had [an ocaml project](https://github.com/dckc/spotter) set up well, it was really a blast and  reasonml has long been on my list of things I'd like to try out.

cc @fabcotech @9rb @tgrospic @jimscarver

**Comment by fabcotech** [comment]
I would be in the favor of using very standard web technologies, react+redux +ts(+1 from me) or vue+redux+ts. If eventually in the future another team forks it or builds on it, its always better to have followed industry standards.

I can put something up very quickly, at least a clean bootstrap project we'll build upon.

**Comment by TheoXD** [comment]
Yeah, I would advise to go with typescript and a component-based mobile-first web framework (Vue/React/Angular), it gets the job done. I personally would recommend typescript+vue+ionic+capacitor as well as vue-class-component, vue-projerty-decorator and typed-vuex.

**Comment by fabcotech** [comment]
capacitor ? in order to anticipate getting it on mobile ??

**Comment by dckc** [comment]
I haven't seen interest from @leithaus nor anyone else in writing reasonml / ocaml.

**Comment by dckc** [comment]
As to other technology choices, I don't have much preference, though I suggest moving that discussion to other issues (or preferably: pull requests).

I have pretty much exhausted the amount of time I want / plan to spend on this project, at least until someone addresses #6 .
